### ISSUE TITLE
Your students cheat on their homework

### ISSUE THREAD

**Issue by Fanxaio** [Homy1/Teachers#2]
Dear teacher, your student Yuxiang-Huang cheated in homework, and every homework was done by someone on the Internet. I have all the evidence and the code of his homework here. I am just a technician, but I didn't know that this was his homework until later. Intentionally not replying to the message, delaying the payment of the agent fee, abusing others and behaving badly. Please reply in time after receiving the email. I have all the evidence here, including the pdf requirements of your homework and the user name of his git education email.

**Comment by Homy1** [comment]
Thank you for your message. I am considering this

**Comment by Homy1** [comment]
Can you please send me all your evidence, including your chat in wechat?
